In [ ]:
# Linear Algeabra is not basic algeabra

# Linear algebra is a branch of mathematics that deals with vector spaces and linear equations

# keywords: Vectors, Matrices , Linear Equations, Vector Spaces, Linear Transformations, Eigenvalues and Eigenvectors, determinant

# As a data scientist learn to remember concepts as a CS student( as programming like arrays , matrix) and also with visual understanding

# This notebook is purely for people who are already familiar with concepts of vector or linear algeabra ....if not read the textbook (essential math for data science)


In [ ]:
# some of the key findings or ideas from vector algeabra

# 1. Always imagine a vector tail starts at the origin of cartesian plane(0,0)
# 2. Python is slow whereas its numeric and scientific libraries are not slow eg:numpy ( which we are going to use for linear algeabra )
# 3. each vector can be represented as group of hat vectors also called basis vectors moving in a certain direction
# 4. operations: scaling, shear, rotate
# 5. when we have two vectors in two different direction they are linearly independent and have this unlimited span 
# 6. when the combination of vectors is stuck on same line then they just limit our span to the same line and this is called linealy dependent.
# 7. why check for linear dependence : A lot of problems become difficult or unsolvable when they are linearly dependent 
# for eg: when we are dealing with system of equations, a linearly dependent set of equations can cause variables to disappear and make the problem unsolvable
# and we use determinant to check for linear dependence for a group of vectors or system of equations
# 8. The flexibility to create any vector you need from two or more vectors becomes invaluable to solve for a solution
# 9. Always use the goal is create some new vector or matrix
# 10. You create new vector by performing some transformations on some vectors 
# 11. Basis vectors acts a ground level transformation for whatever the vector.. so let's call it a sequence of transformations ( like scale,shear,rotate) until you get your final vector or matrix starting with a single vector
# 12. You can't have transformations that are non linear, resulting in curvy or squiggly transformation ..remember it is linear algeabra not non linear algeabra
# 13. If you want true vector algeabra enlightment, think why creating vectors and transforming vectors are actually the same thing.
# It's all a matter of relativity given your basis vectors being a starting point (the most basic starting point i_hat and j_hat) before and after transformation.
# 14. A matrix is really is a transformation expressed as basis vectors
# 15. Non square matrix can transform vector space into fewer or more dimensions
# 16. See matrix multiplication as pulling basis vectors or transformation in a certain way- updated basis* old basis
# 17. A determinant measures how a linear transformation scales an area
# 18. A simple shear or rotate should not affect the determinant as the area will not change which is usually 1 and it is negative when the orientation flips and scaling will increase or decrease the determinant
# 19. If you have a determinant of 0 that means all of the space has been squished into a lesser dimension which is called linear dependence
# 20. Square matrix -- represent linear transformations and a requirement in eigen decomposition
# Identity matrix -- you have undone a transformation and found your starting basis vectors
# Inverse matrix -- It will undoes the transformation of another matrix
# Diagonal matrix -- Desirable in certain computations because they represent simple scalars being applied to a vector space
# Traingular matrix -- Easier to solve systems of equations
# sparse matrix -- To create efficiency by not wasting space storing a bunch of 0's and 1's instead only keep track of the cells that are non zero
# Eigen decomposition is helpful for breaking up matrix into components that are easier to work with
# Eigen vector is literally the vector who has a scalar change but not anything when you do the transformation and that eigen value is the scalar value by which it changed
# There is one eigen vector and eigen value for each dimension of the parent matrix and not alll matrices can be decomposed into an eigen vector and eigen value sometimes complex numbers will even result

In [2]:
# Adding two vectors

from numpy import array

v = array([3,2])
w = array([2,1])
s=v+w
print(s)

[5 3]


In [3]:
# Scaling vectors

scaled_v= 2.0 * v
print(scaled_v)

[6. 4.]


In [4]:
# Matrix multiplication

basis= array([[3,0],[0,2]])
v= array([1,1])
new_v= basis.dot(v)

print(new_v)


[3 2]


In [ ]:
# if you break out the basis vectors and then compose them together into a matrix..just note you need to transpose or swap the columns and rows
# because numpy's array function will consider each vector as  a row rather than a column
# array([1,1],[2,2]) is not same as x = [1,1] and y= [2,2] and array([x,y]) instead it is array([x,y]).transpose()
# use matmul or @ operator to perform matrix multiplication
#To apply these transformations in sequence (shear, then rotate, then scale), we multiply the matrices in reverse order of application: T=S with scale⋅R⋅S with shear 

In [5]:
import numpy as np

# Define the transformation parameters
kx, ky = 1.0, 0.5  # Shear factors
theta = np.radians(30)  # Rotation angle in radians
sx, sy = 2.0, 1.5  # Scale factors

# Shear matrix
shear_matrix = np.array([
    [1, kx],
    [ky, 1]
])

# Rotation matrix
rotation_matrix = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])

# Scale matrix
scale_matrix = np.array([
    [sx, 0],
    [0, sy]
])

# Combine the transformations: Scale -> Rotate -> Shear
combined_matrix = scale_matrix @ rotation_matrix @ shear_matrix

# Define a point to transform
point = np.array([1, 1])

# Apply the combined transformation
transformed_point = combined_matrix @ point

# Print the results
print("Shear Matrix:\n", shear_matrix)
print("Rotation Matrix:\n", rotation_matrix)
print("Scale Matrix:\n", scale_matrix)
print("Combined Transformation Matrix:\n", combined_matrix)
print("Original point:", point)
print("Transformed point:", transformed_point)


Shear Matrix:
 [[1.  1. ]
 [0.5 1. ]]
Rotation Matrix:
 [[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]
Scale Matrix:
 [[2.  0. ]
 [0.  1.5]]
Combined Transformation Matrix:
 [[1.23205081 0.73205081]
 [1.39951905 2.04903811]]
Original point: [1 1]
Transformed point: [1.96410162 3.44855716]


In [6]:
# solving a system of equations using inverse

import numpy as np

# Define the coefficient matrix A and the constant matrix B
A = np.array([[2, 3], [5, 4]])
B = np.array([[8], [14]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

# Print the results
print("Coefficient Matrix (A):")
print(A)
print("\nConstant Matrix (B):")
print(B)
print("\nInverse of Matrix (A):")
print(A_inv)
print("\nSolution (X):")
print(X)


Coefficient Matrix (A):
[[2 3]
 [5 4]]

Constant Matrix (B):
[[ 8]
 [14]]

Inverse of Matrix (A):
[[-0.57142857  0.42857143]
 [ 0.71428571 -0.28571429]]

Solution (X):
[[1.42857143]
 [1.71428571]]


In [7]:
# Constructing original matrix from eigen values and eigen vectors


import numpy as np

# Original matrix
A = np.array([[4, -2],
              [1,  1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Construct the diagonal matrix of eigenvalues
Lambda = np.diag(eigenvalues)

# Eigenvectors matrix (V)
V = eigenvectors

# Inverse of the eigenvectors matrix (V^-1)
V_inv = np.linalg.inv(V)

# Reconstruct the original matrix
A_reconstructed = V @ Lambda @ V_inv

# Print the results
print("Original matrix (A):")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors (V):")
print(V)
print("\nDiagonal matrix of eigenvalues (Lambda):")
print(Lambda)
print("\nInverse of the eigenvectors matrix (V^-1):")
print(V_inv)
print("\nReconstructed matrix (A_reconstructed):")
print(A_reconstructed)


Original matrix (A):
[[ 4 -2]
 [ 1  1]]

Eigenvalues:
[3. 2.]

Eigenvectors (V):
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]

Diagonal matrix of eigenvalues (Lambda):
[[3. 0.]
 [0. 2.]]

Inverse of the eigenvectors matrix (V^-1):
[[ 2.23606798 -2.23606798]
 [-1.41421356  2.82842712]]

Reconstructed matrix (A_reconstructed):
[[ 4. -2.]
 [ 1.  1.]]
